"ciflow/8gpu":
  - .ci/docker/**
  - .github/workflows/**
  - scripts/**
  - tests/**
  - torchtitan/**

"ciflow/rl":
  - torchtitan/experiments/rl/**
  - .github/workflows/integration_test_4gpu_rl.yaml
  - .github/workflows/integration_test_8gpu_rl_h100.yaml
