[job]
dump_folder = "./outputs"
description = "DeepSeek-V3 16B model training"
print_args = false

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 10
disable_color_printing = false
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = false

[model]
name = "deepseek_v3_multi"
flavor = "30B"
hf_assets_path = "./assets/hf/deepseek-moe-16b-base"
# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 2.2e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 200  # lr scheduler warm up, normally 20% of the train steps
decay_ratio = 0.8  # lr scheduler decay ratio, 80% of the train steps
decay_type = "cosine"
min_lr_factor = 0.1

[training]
local_batch_size = 8
seq_len = 4096
max_norm = 1.0  # grad norm clipping
steps = 1000
# dataset = "c4"  # supported datasets: c4_test (2K), c4 (177M)
dataset = "/mnt/wsfuse/htouvron/cwm_32b_data/20250318/github_neo/github_neo_repo_dfs_v3:27,/mnt/wsfuse/htouvron/cwm_32b_data/20250318/llama3/llama3_fiction_fair_copy:0.8,/mnt/wsfuse/htouvron/cwm_32b_data/llama2/arxiv:0.4,/mnt/wsfuse/htouvron/cwm_32b_data/llama2/stackexchange:0.7,/mnt/wsfuse/htouvron/cwm_32b_data/20250214/proof_pile_2/proof_pile_2_open_web_math_train:0.25,/mnt/wsfuse/htouvron/cwm_32b_data/20250214/proof_pile_2/proof_pile_2_algebraic_stack_train:0.15,/mnt/wsfuse/htouvron/cwm_32b_data/20250214/proof_pile_2/proof_pile_2_arxiv_train:0.4,/mnt/wsfuse/htouvron/cwm_32b_data/20250214/dm_mathematics/dm_math_train_easy:0.02,/mnt/wsfuse/htouvron/cwm_32b_data/20250214/dm_mathematics/dm_math_train_medium:0.02,/mnt/wsfuse/htouvron/cwm_32b_data/20250214/dm_mathematics/dm_math_train_hard:0.02,/mnt/wsfuse/htouvron/cwm_32b_data/20250214/aqua_train:0.0002,/mnt/wsfuse/htouvron/cwm_32b_data/20250318/llama3/llama3_galactica_fair_copy:1,/mnt/wsfuse/htouvron/cwm_32b_data/20250318/llama3/llama3_mobius_wiki_all_en_fair_copy:0.1,/mnt/wsfuse/htouvron/cwm_32b_data/20250318/llama3/llama3_math_v1_data_decontaminated_fair_copy:0.8,/mnt/wsfuse/htouvron/cwm_32b_data/20250318/llama3/llama3_math_decontaminated_fair_copy:0.8,/mnt/wsfuse/htouvron/cwm_32b_data/20250318/llama3/llama3_wikipedia_fair_copy:1,/mnt/wsfuse/htouvron/cwm_32b_data/dclm_baseline_1_0:55"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
enable_async_tensor_parallel = false
pipeline_parallel_degree = 1
pipeline_parallel_schedule = "Interleaved1F1B"
expert_parallel_degree = 8
expert_tensor_parallel_degree = 1

[checkpoint]
enable = false
folder = "checkpoint"
interval = 10
last_save_model_only = true
export_dtype = "float32"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem]"

[activation_checkpoint]
mode = "selective"  # ["none", "selective", "full"]
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[compile]
enable=true
components = ["loss"] # ["model", "loss"]

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output", "router.gate"]
moe_fqns_prototype = ["experts"]
