# Kimi K2: EP=64 CP=1 SEQ=24K LBS=1 - 16 nodes (128 GPUs, DP_REPLICATE=2)
# No DeepEP - using standard torch all-to-all for expert parallel

[job]
dump_folder = "./outputs/kimi_k2_ep64_cp1_seq24k_lbs1_16n_disable_force_bl"
description = "Kimi K2: DP_REPLICATE=2 EP=64 CP=1 SEQ=24K LBS=1 16N (force_bl disabled)"

[profiling]
enable_profiling = false

[metrics]
log_freq = 1
disable_color_printing = true

[model]
name = "deepseek_v3"
flavor = "kimi_k2"
hf_assets_path = "/mnt/data/shared/Kimi-K2-Base-BF16"

[optimizer]
name = "AdamW"
lr = 8e-4
eps = 1e-8

# [optimizer]
# name = "Muon"
# lr = 5.5e-6
# eps = 1e-8
# weight_decay = 0.01
# beta1 = 0.9
# beta2 = 0.999
# mu = 0.95
# algorithm = "muon"
# nesterov = false
# adjust_lr = "rms_norm"
# flatten = false
# use_triton = true
# scalar_optimizer = "adamw"
# embedding_optimizer = "adamw"
# head_optimizer = "adamw"
# head_lr_scaling = false
# scalar_lr_factor = 1
# embedding_lr_factor = 1
# head_lr_factor = 1.0
# routing_lr_factor = 1.0
# expert_lr_factor = 1.0

[lr_scheduler]
warmup_steps = 20
decay_ratio = 0.8
decay_type = "linear"
min_lr_factor = 0.0

[training]
dtype = "bfloat16"
local_batch_size = 1
seq_len = 24576
max_norm = 1.0
steps = 1000
dataset = "c4_test"
enable_cpu_offload = true

[parallelism]
data_parallel_shard_degree = -1
expert_parallel_degree = 64
context_parallel_degree = 1

[activation_checkpoint]
mode = "full"

[compile]
enable = true
components = ["loss"]

[debug]
moe_force_load_balance = false

[comm]
init_timeout_seconds = 1800
train_timeout_seconds = 1800
