input:
  h5_folder: /p/data1/nxtaim/proprietary_samples/avl/AvlTest_2022-04-06_07-00-49_2011_562134/ # Path to folder containing HDF5 files
  dataset_names: # List of dataset (topic) names to use, or leave empty/null for all
    #- camera_0
    #- camera_1
    - back
    - front
dataloader:
  batch_size: 12
  num_workers: 0

transforms:
  resize: [256, 256]
  to_tensor: true
  normalize: true

augmentation: resize_center # or random_resize_center
size: 1024
scale_min: 0.15
scale_max: 0.5
num_frames: 1
frame_rate: 10
