name: Check Links

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: link-check-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mistune pytest pytest-check-links pytest-timeout pytest-xdist

      - name: Check links
        run: |
          FILES=$(find . -name "*.md")

          # -n auto: parallel execution
          # -p no:python: skip discovery imports
          pytest -v \
            -p no:python \
            -n auto \
            --check-links \
            --timeout 5 \
            $FILES
