name: 8 AMD GPU Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
concurrency:
  group: unit-test${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  build-test:
    uses: pytorch/test-infra/.github/workflows/linux_job_v2.yml@main
    with:
      runner: linux.rocm.gpu.mi300.8
      gpu-arch-type: rocm
      gpu-arch-version: "6.3"
      upload-artifact: outputs
      use-custom-docker-registry: false
      script: |
        set -eux
        # The generic Linux job chooses to use base env, not the one setup by the image
        conda install -c conda-forge jq -y
        CONDA_ENV=$(conda env list --json | jq -r ".envs | .[-1]")
        conda activate "${CONDA_ENV}"
        pip config --user set global.progress_bar off
        pip install -r requirements.txt
        python -m pip install --force-reinstall --pre torch --index-url https://download.pytorch.org/whl/nightly/rocm6.3
        USE_CPP=0 python -m pip install --pre torchao --index-url https://download.pytorch.org/whl/nightly/cu126
        # There's perrmission issue in uploading files in artifacts-to-be-uploaded on AMD nodes, thus skip it by creating and storing
        # results in generated-artifacts.
        mkdir generated-artifacts
        python ./tests/integration_tests_amd.py generated-artifacts --ngpu 8
