name: Lychee Link Check (Nightly)

on:
  schedule:
    # Run nightly at 07:00 UTC
    - cron: '0 7 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Restore Lychee cache
        uses: actions/cache@v5
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Lychee URL Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --cache
            --exclude-path "(^|/)\.[^/]+/"
            --root-dir .
            --accept "200,403,429,503"
            --exclude "http://localhost:.*"
            --exclude "http://127.0.0.1:.*"
            --exclude "tcp://localhost:.*"
            --max-retries 30
            --retry-wait-time 60
            --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
            "./**/*.md"
            "./**/*.py"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
