name: Lint

on:
  pull_request:

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install Lychee (Latest Release)
        run: |
          # Query GitHub API for the latest release tag
          LATEST_TAG=$(curl -s https://api.github.com/repos/lycheeverse/lychee/releases/latest | jq -r .tag_name)
          echo "Installing Lychee version: $LATEST_TAG"

          URL="https://github.com/lycheeverse/lychee/releases/download/${LATEST_TAG}/lychee-x86_64-unknown-linux-gnu.tar.gz"

          # Load the archive, extract into temp folder, move the binary, delete the rest
          mkdir -p lychee_install
          curl -sLO "$URL"
          tar -xzf "lychee-x86_64-unknown-linux-gnu.tar.gz" -C lychee_install
          sudo mv lychee_install/lychee /usr/local/bin/
          rm -rf lychee_install "lychee-x86_64-unknown-linux-gnu.tar.gz"

          # Verify installation
          lychee --version

      - name: Install dependencies and lint utilities
        run: |
          python -m pip install -r requirements.txt -r requirements-dev.txt
          python -m pip install --force-reinstall --pre --index-url https://download.pytorch.org/whl/nightly/cu130 torch
          pre-commit install-hooks

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v45.0.6

      - name: Lint modified files
        run: pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Check links with Lychee
        run: |
          pre-commit run lychee-link-checker --all-files
