name: TODO Debt Tracker

on:
  # 1. Manual trigger
  workflow_dispatch:

  # 2. Automatic trigger (Once a day at midnight UTC)
  schedule:
    - cron: '0 0 * * *'

  # 3. Triggered if the script or the action configuration is changed
  push:
    paths:
      - .github/workflows/todo_debt_tracker.yaml
      - .github/scripts/todo_debt_tracker.py

jobs:
  check_todos:
    name: Generate Report
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # read access to issues and pull-requests to allow the gh api calls to work
      # against private repositories or to fetch metadata like titles.
      pull-requests: read
      issues: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # Fetch all history so git blame can identify authors correctly
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Generate TODO Status Report
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/todo_debt_tracker.py
