# torchtitan Config.toml
# NOTE: this toml config is a preset for 8 H100 GPUs.

[job]
dump_folder = "./24b_test_2"
description = "Mistral 24B training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = true
wandb_project = "artem_deephermes_24b_simpletrainer"
seed = 42

[model]
name = "mistral3"
flavor = "24B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm
tokenizer_path = "mistralai/Mistral-Small-3.1-24B-Instruct-2503"
#tokenizer_path = "/mnt/weka/home/artem/new2/simple-trainer/mistral-2503-base-hf"
# converters = "float8"

[optimizer]
name = "AdamW"
lr = 1e-6

[training]
base_model_dir = "/mnt/weka/home/artem/new2/simple-trainer/mistral-2503-base-dcp"
train_type = "sft"
seed=42
batch_size = 2
seq_len = 16384
gradient_accumulation_steps = 1
warmup_steps = 200  # lr scheduler warm up
lr_ramp_type = "cosine"
lr_ramp_end_lr_ratio = 0.0
max_norm = 1.0  # grad norm clipping
steps = 700
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 8
compile = false 
dataset = "metamath"

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 72000
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'full'  # ['none', 'selective', 'full']
#selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_fsdp_float8_all_gather = true
precompute_float8_dynamic_scale_for_fsdp = true
